#! /usr/bin/bash

# bspwm config
bspc config border_width        2
bspc config window_gap          4

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config ignore_ewmh_focus   true
bspc config click_to_focus      true

# color
bspc config focused_border_color "#517ba2"
bspc config presel_feedback_color "#517ba2"

# desktops
monitors=$(bspc query -M)
array=(${monitors})

if [ ${#array[@]} -eq 2 ]; then
    bspc monitor ${array[0]} -d web games
    bspc monitor ${array[1]} -d term misc
else
    bspc monitor -d term web games misc
fi

# application rules
bspc rule -a Opera desktop=web
bspc rule -a Steam follow=off state=floating desktop=games
bspc rule -a Galculator state=floating
bspc rule -a RocketLeague border=off
bspc rule -a Nvidia-settings state=floating
bspc rule -a obs state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a "TeamSpeak 3" state=floating

# hotkey daemon
sxhkd &

# panel
~/.config/bspwm/panel &
