#! /bin/sh

# bspwm config
bspc config border_width        2
bspc config window_gap          4

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config auto_cancel true

# color
bspc config focused_border_color "#7e7f89"

# desktops
bspc monitor -d term web games misc

# application rules
bspc rule -a Chromium desktop=web

# hotkey daemon
sxhkd &

# panel
~/.config/bspwm/panel &
