#! /bin/sh

# bspwm config
bspc config border_width        2
bspc config window_gap          4

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config ignore_ewmh_focus   true
bspc config auto_cancel true

# color
bspc config focused_border_color "#517ba2"

# desktops
bspc monitor DVI-I-1 -d web games 
bspc monitor HDMI-0 -d term misc

# application rules
bspc rule -a chromium desktop=web
bspc rule -a Steam follow=off border=off desktop=games

# hotkey daemon
sxhkd &

# panel
~/.config/bspwm/panel &
